/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.*;
import controlador.*;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Jean Pierre
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    static Alumno alumno;
    static Docente docente;
    Date dt = new Date();
//Instaciando controladores
    SimpleDateFormat sd = new SimpleDateFormat("yyyy-MM-dd");
    ControladorAlumno ca = new ControladorAlumno();

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        /*Evitar Editar Datos*/
        txtnombre.setEditable(false);
        txtapellido.setEditable(false);
        txtcorreo.setEditable(false);
        txtdni.setEditable(false);
        txttelefono.setEditable(false);
        txtusuario.setEditable(false);
        txtedad.setEditable(false);
        datefechanacimiento.setEnabled(false);
        txtsexo.setEditable(false);

        /*Fin Editar Datos*/
        VentanaPerfil.setVisible(false);
    }

    public void closeIframes() {
        this.VentanaPerfil.setVisible(false);

    }

    public Image generarImagenCita(byte[] bytes) throws IOException {
        BufferedImage imagen = null;
        try {
            InputStream in = new ByteArrayInputStream(bytes);
            imagen = ImageIO.read(in);
        } catch (Exception e) {
        }
        return imagen;
    }

    public String VectorTipo(int id_tipo) {
        String vec[] = {"", "Estudiante", "Docente"};
        return vec[id_tipo];
    }

    public int FechaDif(String cad1, String cad2) {
        //primero las cadenas convertirlos a fechas
        long dias;
        try {
            Date f1 = sd.parse(cad1);
            Date f2 = sd.parse(cad2
            );
            Calendar c1 = Calendar.getInstance();
            Calendar c2 = Calendar.getInstance();
            //las fechas convertirlos a calendario
            c1.setTime(f1);
            c2.setTime(f2);
            dias = (c2.getTimeInMillis() - c1.getTimeInMillis()) / (1000 * 60 * 60 * 24);
        } catch (Exception ex) {
            dias = 0;
        }
        return (int) dias;
    }

    void verPerfil() {
        if (alumno != null) {
            try {
                FotoPerfil.setIcon(new ImageIcon(generarImagenCita(alumno.getAvatar()).getScaledInstance(FotoPerfil.getWidth(), FotoPerfil.getHeight(), Image.SCALE_DEFAULT)));
            } catch (IOException ex) {
                Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            txtnombre.setText(alumno.getNombre());
            txtapellido.setText(alumno.getApellido());
            txtcorreo.setText(alumno.getCorreo());
            txttelefono.setText("" + alumno.getTelefono());
            txtsexo.setText(alumno.getSexo());
            txtdni.setText("" + alumno.getDNI());
            txtusuario.setText(VectorTipo(alumno.getId_Tipo()));
            datefechanacimiento.setDate(alumno.getFecha_Nacimiento());
            txtedad.setText("" + (FechaDif(sd.format(alumno.getFecha_Nacimiento()), sd.format(dt))) / 365);
        } else {
            try {
                FotoPerfil.setIcon(new ImageIcon(generarImagenCita(docente.getAvatar()).getScaledInstance(FotoPerfil.getWidth(), FotoPerfil.getHeight(), Image.SCALE_DEFAULT)));
            } catch (IOException ex) {
                Logger.getLogger(frmMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }

            txtnombre.setText(docente.getNombre());
            txtapellido.setText(docente.getApellido());
            txtcorreo.setText(docente.getCorreo());
            txttelefono.setText("" + docente.getTelefono());
            txtsexo.setText(docente.getSexo());
            txtdni.setText("" + docente.getDNI());
            txtusuario.setText(VectorTipo(docente.getId_Tipo()));
            datefechanacimiento.setDate(docente.getFecha_Nacimiento());
            txtedad.setText("" + (FechaDif(sd.format(docente.getFecha_Nacimiento()), sd.format(dt))) / 365);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        VentanaPerfil = new javax.swing.JInternalFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtsexo = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtusuario = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        datefechanacimiento = new com.toedter.calendar.JDateChooser();
        FotoPerfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Perfil = new javax.swing.JMenu();
        MenuPerfil = new javax.swing.JMenuItem();
        MenuEditarPerfil = new javax.swing.JMenuItem();
        MenuCerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(626, 391));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo.jpg"))); // NOI18N

        VentanaPerfil.setPreferredSize(new java.awt.Dimension(626, 391));
        VentanaPerfil.setVisible(true);
        VentanaPerfil.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Apellido:");
        VentanaPerfil.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, -1));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nombre:");
        VentanaPerfil.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Correo:");
        VentanaPerfil.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 60, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Telefono:");
        VentanaPerfil.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 70, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sexo:");
        VentanaPerfil.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 40, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("DNI:");
        VentanaPerfil.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 30, -1));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Fecha de Nacimiento:");
        VentanaPerfil.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 160, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Tipo de Usuario:");
        VentanaPerfil.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Edad:");
        VentanaPerfil.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 40, -1));
        VentanaPerfil.getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 160, -1));
        VentanaPerfil.getContentPane().add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 160, -1));
        VentanaPerfil.getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 160, -1));
        VentanaPerfil.getContentPane().add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 160, -1));
        VentanaPerfil.getContentPane().add(txtsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 160, -1));
        VentanaPerfil.getContentPane().add(txtdni, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 160, -1));
        VentanaPerfil.getContentPane().add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 160, -1));
        VentanaPerfil.getContentPane().add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 160, -1));
        VentanaPerfil.getContentPane().add(datefechanacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 160, -1));

        FotoPerfil.setBorder(new javax.swing.border.MatteBorder(null));
        VentanaPerfil.getContentPane().add(FotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 180, 210));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo1.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(626, 391));
        jLabel2.setMinimumSize(new java.awt.Dimension(626, 391));
        jLabel2.setPreferredSize(new java.awt.Dimension(626, 391));
        VentanaPerfil.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 410));

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(VentanaPerfil, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VentanaPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(VentanaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jDesktopPane1);

        Perfil.setText("Perfil");

        MenuPerfil.setText("Ver Perfil");
        MenuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPerfilActionPerformed(evt);
            }
        });
        Perfil.add(MenuPerfil);

        MenuEditarPerfil.setText("Editar Perfil");
        Perfil.add(MenuEditarPerfil);

        MenuCerrarSesion.setText("Cerrar Sesión");
        Perfil.add(MenuCerrarSesion);

        jMenuBar1.add(Perfil);

        jMenu2.setText("Cursos");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Notas");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPerfilActionPerformed
        closeIframes();
        VentanaPerfil.setVisible(true);
        verPerfil();
    }//GEN-LAST:event_MenuPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FotoPerfil;
    private javax.swing.JMenuItem MenuCerrarSesion;
    private javax.swing.JMenuItem MenuEditarPerfil;
    private javax.swing.JMenuItem MenuPerfil;
    private javax.swing.JMenu Perfil;
    private javax.swing.JInternalFrame VentanaPerfil;
    private com.toedter.calendar.JDateChooser datefechanacimiento;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsexo;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
